### ISSUE TITLE
About CBS Execution Commands

### ISSUE THREAD

**Issue by mayo233** [chenzhike110/MAPF-solver#1]
Hi, I would like to run cbs.py in the CBS folder. However, when I run $python cbs.py -input.yaml /Users/suzuaaaa/MAPF-solver/cbs, cbs.py: error: the following arguments are required: output error. What arguments should I give?

**Comment by chenzhike110** [comment]
```
python cbs.py --param input.yaml --output output.yaml
```
intput.yaml refers to the map, start positions and target positions
the result path of agent will be dumped in output.yaml
